<?php

/**
 * Implements hook_views_api().
 */
function catchsmile_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'catchsmile') . '/views',
  );
}


/**
 * Implements hook_page_build().
 */
function catchsmile_page_build(&$page) {
  if (arg(0) == 'node' && user_is_anonymous()) {
    drupal_add_library('system', 'jquery.cookie', TRUE);
    // Send necessary parameters to the JavaScript.
    drupal_add_js(
      array(
        'catchsmile' => array(
          'serviceUri' => url('endpoint1/catchsmile/count'),
          'refreshInterval' => 5000
        )
      ),
      'setting'
    );
    drupal_add_js(drupal_get_path('module', 'catchsmile') . '/js/catchsmile.js');
  }
}

/**
 * Implements hook_services_resources().
 */
function catchsmile_services_resources() {
  return array(
    'catchsmile' => array(
      'actions' => array(
        'count' => array(
          'access callback'         => 'user_access',
          'access arguments'        => array('access content'),
          'access arguments append' => FALSE,
          'callback' => '_catchsmile_calculate_count',
        ),
      ),
    ),
  );
}

/**
 * Action calculate_count callback.
 */
function _catchsmile_calculate_count() {
  $count = db_select('node')
    ->addTag('node_access')
    ->condition('type', 'catchsmile')
    ->countQuery()
    ->execute()
    ->fetchField();

  $result = new stdClass();
  $result->count = $count;

  return $result;
}

